language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 hello.c -o hello
  - clang -coverage -O0 foo.c -o foo
  - ./hello
  - ./foo

#  - gcov hello.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
